#!/usr/bin/env bash
# VIM cheat sheet: https://vim.rtorr.com/
set -e
mkdir -p ~/.config/nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
curl -fLo ~/.config/nvim/init.vim \
  https://raw.githubusercontent.com/Muvon/linux-bintools/master/config/nvim/init.vim
nvim +'PlugInstall --sync' +qa
mkdir -p ~/.config/nvim/colors
curl -sSL https://raw.githubusercontent.com/abra/vim-obsidian/master/colors/obsidian.vim > ~/.config/nvim/colors/obsidian.vim
if [[ "$(whoami)" == "root" ]]; then
  curl -sL install-node.vercel.app/lts | bash
  curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
fi
nvim +CocInstall coc-tabnine coc-rust-analyzer coc-html coc-tsserver @yaegassy/coc-intelephense +qall

# Install patched fonts on osx for NERDTree plugin
if which brew; then
	brew tap homebrew/cask-fonts
	brew install --cask font-fira-code-nerd-font
fi

