#!/usr/bin/env bash
# VIM cheat sheet: https://vim.rtorr.com/
set -e
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fLo ~/.vimrc \
  https://raw.githubusercontent.com/Muvon/linux-bintools/master/config/.vimrc
vim +'PlugInstall --sync' +qa
mkdir -p ~/.vim/colors
curl -sSL https://raw.githubusercontent.com/abra/vim-obsidian/master/colors/obsidian.vim > ~/.vim/colors/obsidian.vim
if [[ "$(whoami)" == "root" ]]; then
  curl -sL install-node.vercel.app/lts | bash
  curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
fi
vim +CocInstall coc-tabnine +qall

# Install patched fonts on osx for NERDTree plugin
if which brew; then
	brew tap homebrew/cask-fonts
	brew install --cask font-fira-code-nerd-font
fi

